cherry-pick fix for ceph-volume exception when creating an OSD
Without the patch, creating an OSD would fail with:
> AttributeError: 'EntryPoints' object has no attribute 'get'

Thanks to Fabian Grünbichler for quickly finding the fix upstream!

Signed-off-by: Fiona Ebner <f.ebner@proxmox.com>
Link: https://lore.proxmox.com/20250623141632.409074-1-f.ebner@proxmox.com
(cherry picked from commit af40d88dc3756c783031957642d0a78a2815d191)
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>